select * from customer_shopping_behavior;

---total revenue generated by male vs female customer?
select gender,sum(purchase_amount) as amount from customer_shopping_behavior
group by gender;

-- which customer uses discount but spend more than average purchased amount
select customer_id,purchase_amount 
from customer_shopping_behavior 
where discount_applied = 'YES' 
and  
(select avg(purchase_amount) from customer_shopping_behavior)<=purchase_amount;

---what r the 5 product with highest average review rating

select top 5
item_purchased ,
Round(cast(avg(review_rating) as numeric),2) as "average review product"
from customer_shopping_behavior
group by item_purchased
order by avg(review_rating) desc ;

--compare average prucahse amount between express and standard shipping 

select shipping_type,Round(avg(purchase_amount),2) as "average amount" 
from customer_shopping_behavior
where shipping_type in ('Standard','Express')
group by shipping_type;

-- ddo subscribe customer spend mroe?compare avg spend and ttoal revenue between 
--subscribers and non subscribers

select count(customer_id) as count ,subscription_status,
round(avg(purchase_amount),2) as Purchased_Amount,
round(Sum(purchase_amount),2) as total_revenue
from customer_shopping_behavior
group by subscription_status
order by Purchased_Amount,total_revenue desc;


---which 5 products have the highest pruchases with discount applied 
select top 5 
item_purchased,
   ROUND(
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 1.0 / COUNT(*) * 100,
        2
    ) AS discount_rate
	from customer_shopping_behavior
group by item_purchased
order by discount_rate desc;

---segemnt customer inrto new,loyal and returning and based on previous purchases and show total count

with customer_segment as(
select customer_id,previous_purchases,
case when previous_purchases = 1 THEN 'New' 
when previous_purchases between 2 and 10 THEN 'Returning'
ELSE 'loyal' end as customer_type
from customer_shopping_behavior 
)

select customer_type ,count(customer_id) as "number of customers"
from customer_segment
group by customer_type ;


--top 3 most purchaseed product in each category:

with table1 as(

select category,count(customer_id) as countt,item_purchased,
ROW_NUMBER()OVER (Partition by category order by count(customer_id) desc) as item_rank
from customer_shopping_behavior
group by category,item_purchased
)

select 
item_rank,category,countt,item_purchased from table1
where item_rank<=3;


--are customer who are repeat buyers (more than 5 perchases)likely to subsribe?

with me as (
select subscription_status,
count(customer_id) as countt
from customer_shopping_behavior
where previous_purchases>=5
group by subscription_status
)
select subscription_status,countt from me
order by subscription_status asc;

---revenue contribution of each age group

with meee as (
select sum(purchase_amount) as revenue,
age_group 
from customer_shopping_behavior
group by age_group
)
select revenue,age_group from meee
order by revenue desc;